package View;

import controller.DifeanceObservable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sahan Geesara
 */
public class MainController extends javax.swing.JFrame {
    private DifeanceObservable Observable;
    /**
     * Creates new form MainController
     */
    public MainController(DifeanceObservable Observable) {
        setVisible(true);
        this.Observable=Observable;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDefence = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        areaClear = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sliderPosition = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTank = new javax.swing.JTextArea();
        privateCheakBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHelicopter = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSubmarine = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sendTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbDefence.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbDefence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select defence", "Helicopter", "Tank", "Submarine" }));
        cmbDefence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDefenceActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDefence, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, 214, 42));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Collect Information");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 19, -1, -1));

        areaClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        areaClear.setText("Area CLear");
        areaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaClearActionPerformed(evt);
            }
        });
        getContentPane().add(areaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 22, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 121, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Ammo Amount");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 217, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Fuel Amount");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 179, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Position");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 306, -1, -1));

        sliderPosition.setMajorTickSpacing(20);
        sliderPosition.setPaintLabels(true);
        sliderPosition.setPaintTicks(true);
        sliderPosition.setSnapToTicks(true);
        sliderPosition.setValue(0);
        sliderPosition.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sliderPositionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(sliderPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 356, 522, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText(""); // NOI18N
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setAutoscrolls(true);

        txtTank.setColumns(20);
        txtTank.setRows(5);
        jScrollPane1.setViewportView(txtTank);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 446, 275, 179));

        privateCheakBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        privateCheakBox.setText("Send Private ");
        privateCheakBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateCheakBoxActionPerformed(evt);
            }
        });
        getContentPane().add(privateCheakBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 285, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText(""); // NOI18N
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setAutoscrolls(true);

        txtHelicopter.setColumns(20);
        txtHelicopter.setRows(5);
        jScrollPane2.setViewportView(txtHelicopter);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 236, 179));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setToolTipText(""); // NOI18N
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setAutoscrolls(true);

        txtSubmarine.setColumns(20);
        txtSubmarine.setRows(5);
        jScrollPane3.setViewportView(txtSubmarine);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 446, 275, 179));

        btnSend.setBackground(new java.awt.Color(0, 153, 153));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 356, -1, -1));

        jLabel5.setText("Submarine");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, -1, -1));

        sendTextArea.setColumns(20);
        sendTextArea.setRows(5);
        jScrollPane4.setViewportView(sendTextArea);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 106, 296, 143));

        jLabel6.setText("Helicopter");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 654, -1, -1));

        jLabel7.setText("Tank");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void privateCheakBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateCheakBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privateCheakBoxActionPerformed

    private void cmbDefenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDefenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDefenceActionPerformed

    private void sliderPositionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sliderPositionAncestorAdded
        // TODO add your handling code here:
          Observable.setSliderValueInBtn(sliderPosition.getValue());
    }//GEN-LAST:event_sliderPositionAncestorAdded

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if(privateCheakBox.isSelected()){
            if(cmbDefence.getSelectedIndex()==1){
               Observable.setPrivateMsg1("Main Controller : "+sendTextArea.getText());
            }else if(cmbDefence.getSelectedIndex()==2){
               Observable.setPrivateMsg2("Main Controller : "+sendTextArea.getText());
            }else if(cmbDefence.getSelectedIndex()==3){
               Observable.setPrivateMsg3("Main Controller : "+sendTextArea.getText());
            }
       }else{
           Observable.setMsgPublic("Main Controller : "+sendTextArea.getText());
       }
    }//GEN-LAST:event_btnSendActionPerformed

    private void areaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaClearActionPerformed
        // TODO add your handling code here:
            Observable.setArea(areaClear.isSelected());
    }//GEN-LAST:event_areaClearActionPerformed

     public void setHelicopterMassage(String msg){
        txtHelicopter.append(msg);
    }
    
    public void setankMassage(String msg){
        txtTank.append(msg);
    }
 
    public void setSubMarineMassage(String msg){
        txtSubmarine.append(msg);
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox areaClear;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cmbDefence;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JCheckBox privateCheakBox;
    private javax.swing.JTextArea sendTextArea;
    private javax.swing.JSlider sliderPosition;
    private javax.swing.JTextArea txtHelicopter;
    private javax.swing.JTextArea txtSubmarine;
    private javax.swing.JTextArea txtTank;
    // End of variables declaration//GEN-END:variables
}
