package View;

import interfaces.Observer;

import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sahan Geesara
 */
public class Submarine extends javax.swing.JFrame implements Observer{
    private MainController mainController;
    private int oxegenLevel = 100;
    private int energyLevel = 100;
    /**
     * Creates new form Helicopter
     */
    public Submarine(MainController mainController) {
        setTitle("Submarine");
        this.mainController=mainController;
        initComponents();
        setVisible(true);
        btnTomahakMissile.setEnabled(false);        
        btnTridentMissile.setEnabled(false);
        btnMissile.setEnabled(false);
        btnShhot.setEnabled(false);
        oxygen();
        energy();
        spiSolder.setValue(80);
        spiAmmo.setValue(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaClearMsg = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        btnTridentMissile = new javax.swing.JButton();
        btnShhot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMassege = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        spiAmmo = new javax.swing.JSpinner();
        spiSolder = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chbPesition = new javax.swing.JCheckBox();
        btnTomahakMissile = new javax.swing.JButton();
        slider2 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        display1 = new javax.swing.JTextField();
        display2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaClearMsg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        areaClearMsg.setText("Are Not Cleared");
        getContentPane().add(areaClearMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 34, 170, -1));

        slider1.setMajorTickSpacing(20);
        slider1.setOrientation(javax.swing.JSlider.VERTICAL);
        slider1.setPaintLabels(true);
        slider1.setPaintTicks(true);
        slider1.setValue(100);
        getContentPane().add(slider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 144, 446));

        btnTridentMissile.setBackground(new java.awt.Color(102, 102, 255));
        btnTridentMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnTridentMissile.setText("Trident Missile");
        btnTridentMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnTridentMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 185, 145, 44));

        btnShhot.setBackground(new java.awt.Color(102, 102, 255));
        btnShhot.setForeground(new java.awt.Color(255, 255, 255));
        btnShhot.setText("Shoot");
        btnShhot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShhotActionPerformed(evt);
            }
        });
        getContentPane().add(btnShhot, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 87, 145, 44));

        btnMissile.setBackground(new java.awt.Color(102, 102, 255));
        btnMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnMissile.setText("soner Operation");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 87, 145, 44));

        txtMassege.setColumns(20);
        txtMassege.setRows(5);
        jScrollPane1.setViewportView(txtMassege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 277, 562, 204));

        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });
        getContentPane().add(txtMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 499, 436, -1));

        btnSend.setBackground(new java.awt.Color(0, 153, 153));
        btnSend.setText("Send");
        btnSend.setToolTipText("");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 499, -1, -1));
        getContentPane().add(spiAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 95, -1, -1));
        getContentPane().add(spiSolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ammo Controller");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 93, 202, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Solder Controller");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 34, 202, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 50, 5));

        chbPesition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chbPesition.setText("Position");
        chbPesition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPesitionActionPerformed(evt);
            }
        });
        getContentPane().add(chbPesition, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 137, -1, -1));

        btnTomahakMissile.setBackground(new java.awt.Color(102, 102, 255));
        btnTomahakMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnTomahakMissile.setText("Tomahak Missile");
        btnTomahakMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomahakMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomahakMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 185, 145, 44));

        slider2.setMajorTickSpacing(20);
        slider2.setOrientation(javax.swing.JSlider.VERTICAL);
        slider2.setPaintLabels(true);
        slider2.setPaintTicks(true);
        slider2.setValue(100);
        getContentPane().add(slider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 144, 446));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Enargy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 34, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Oxigent");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 38, -1, -1));

        display1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(display1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, -1, -1));

        display2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(display2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTridentMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTridentMissileActionPerformed

    private void btnShhotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShhotActionPerformed
        // TODO add your handling code here:
         if ((int) spiAmmo.getValue() != 0) {
            spiAmmo.setValue((int) spiAmmo.getValue() - 2);
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "⚠️ Out of Ammo! Refill required to continue combat operations\n                             Do You Want to Refill", "Warning", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                spiAmmo.setValue(200);
            }
        }
    }//GEN-LAST:event_btnShhotActionPerformed

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed
        // TODO add your handling code here:
          if ((int) spiSolder.getValue() != 0) {
            spiSolder.setValue((int) spiSolder.getValue() - 2);
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "⚠️ Out of Ammo! Refill required to continue combat operations\n                             Do You Want to Refill", "Warning", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                spiSolder.setValue(200);
            }
        }
    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
       mainController.setSubMarineMassage("Subnarine : "+txtMsg.getText()+"\n");
    }//GEN-LAST:event_btnSendActionPerformed

    private void chbPesitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPesitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPesitionActionPerformed

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgActionPerformed

    private void btnTomahakMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomahakMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTomahakMissileActionPerformed

      @Override
    public void setAreaClear(boolean isClear){
         if(isClear==true){
           areaClearMsg.setText("Area is Clear");
       }else{
           areaClearMsg.setText("Area is Not Clear");
       }
    }
    @Override
    public void setBtnValue(int value){
        if(chbPesition.isSelected()){
            if(value>20){
                btnShhot.setEnabled(true);
                btnShhot.setBackground( Color.GREEN);
            }else{
                btnShhot.setEnabled(false);
                btnShhot.setBackground(new Color(102,102,255));
            }
            if(value>40){
                btnMissile.setEnabled(true);
                btnMissile.setBackground(Color.GREEN);
            }else{
                btnMissile.setEnabled(false);
                btnMissile.setBackground(new Color(102,102,255));
            }
            if(value>60){
                btnTomahakMissile.setEnabled(true);
                btnTomahakMissile.setBackground(Color.GREEN);
            }else{
                btnTomahakMissile.setEnabled(false);
                btnTomahakMissile.setBackground(new Color(102,102,255));
            }
            if(value>80){
                btnTridentMissile.setEnabled(true);
                btnTridentMissile.setBackground(Color.GREEN);
            }else{
                btnTridentMissile.setEnabled(false);
                btnTridentMissile.setBackground(new Color(102,102,255));
            }
        }else{
            btnShhot.setEnabled(false);
            btnTomahakMissile.setEnabled(false);
            btnTridentMissile.setEnabled(false);
            btnMissile.setEnabled(false);
        }
    }
    
      public void oxygen() {
        new Thread(() -> {
            while (true) {
                slider1.setValue(oxegenLevel--);
                display1.setText(oxegenLevel + "%");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Submarine.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (oxegenLevel == 0) {
                    int choice = JOptionPane.showConfirmDialog(
                            null,
                            "Submarine has no oxygen left!\nDo you want to refill?",
                            "Oxygen Depleted",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );
                    if (choice == JOptionPane.YES_OPTION) {
                        oxegenLevel = 100;
                    } else {
                        JOptionPane.showMessageDialog(null, "Submarine has Left 😐❌", "Left", JOptionPane.ERROR_MESSAGE);
                        dispose();
                    }
                }
            }
        }).start();

    }

    public void energy() {
        new Thread(() -> {
            while (true) {
                slider2.setValue(energyLevel--);
                display2.setText(energyLevel + "%");
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Submarine.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (energyLevel == 0) {
                    int choice = JOptionPane.showConfirmDialog(
                            null,
                            "Submarine has no Energy left!\nDo you want to refill?",
                            "Energy Depleted",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );
                    if (choice == JOptionPane.YES_OPTION) {
                        energyLevel = 100;
                    } else {
                        JOptionPane.showMessageDialog(null, "Submarine has Left 😐❌", "Left", JOptionPane.ERROR_MESSAGE);
                        dispose();
                    }
                }
            }
        }).start();

    }
    @Override
    public void setMassageOtherBoxes(String massage){
        txtMassege.setText(massage);
    }
    @Override
    public void setprivateMassage(String massage){}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaClearMsg;
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShhot;
    private javax.swing.JButton btnTomahakMissile;
    private javax.swing.JButton btnTridentMissile;
    private javax.swing.JCheckBox chbPesition;
    private javax.swing.JTextField display1;
    private javax.swing.JTextField display2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JSpinner spiAmmo;
    private javax.swing.JSpinner spiSolder;
    private javax.swing.JTextArea txtMassege;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
