package View;

import interfaces.Observer;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sahan Geesara
 */
public class Tank extends javax.swing.JFrame implements Observer {
   private MainController mainController;
    /**
     * Creates new form Helicopter
     */
    public Tank(MainController mainController) {
        this.mainController=mainController;
        setTitle("Tank");
        initComponents();
        setVisible(true);
        btnRotate.setEnabled(false);        
        btnRedar.setEnabled(false);
        btnMissile.setEnabled(false);
        btnShhot.setEnabled(false);
        
        spiSolder.setValue(500);
        spiAmmo.setValue(200);
        
        jSlider1.addChangeListener(new ChangeListener() {
           @Override
           public void stateChanged(ChangeEvent e) {
               setSlider(jSlider1.getValue());
           }
       });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaClearMsg = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        btnRotate = new javax.swing.JButton();
        btnShhot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMassege = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        spiAmmo = new javax.swing.JSpinner();
        spiSolder = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chbPesition = new javax.swing.JCheckBox();
        btnRedar = new javax.swing.JButton();
        display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaClearMsg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        areaClearMsg.setText("Are Not Cleared");
        getContentPane().add(areaClearMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 34, 170, -1));

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 144, 492));

        btnRotate.setBackground(new java.awt.Color(102, 102, 255));
        btnRotate.setForeground(new java.awt.Color(255, 255, 255));
        btnRotate.setText("Rotet Operation");
        btnRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateActionPerformed(evt);
            }
        });
        getContentPane().add(btnRotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 185, 145, 44));

        btnShhot.setBackground(new java.awt.Color(102, 102, 255));
        btnShhot.setForeground(new java.awt.Color(255, 255, 255));
        btnShhot.setText("Shoot");
        btnShhot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShhotActionPerformed(evt);
            }
        });
        getContentPane().add(btnShhot, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 87, 145, 44));

        btnMissile.setBackground(new java.awt.Color(102, 102, 255));
        btnMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnMissile.setText("Missile Operation");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 87, 145, 44));

        txtMassege.setColumns(20);
        txtMassege.setRows(5);
        jScrollPane1.setViewportView(txtMassege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 277, 562, 204));

        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });
        getContentPane().add(txtMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 499, 436, -1));

        btnSend.setBackground(new java.awt.Color(0, 153, 153));
        btnSend.setText("Send");
        btnSend.setToolTipText("");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 499, -1, -1));
        getContentPane().add(spiAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 95, -1, -1));
        getContentPane().add(spiSolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ammo Controller");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 93, 202, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Solder Controller");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 44, 202, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 50, 5));

        chbPesition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chbPesition.setText("Position");
        chbPesition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPesitionActionPerformed(evt);
            }
        });
        getContentPane().add(chbPesition, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 137, -1, -1));

        btnRedar.setBackground(new java.awt.Color(102, 102, 255));
        btnRedar.setForeground(new java.awt.Color(255, 255, 255));
        btnRedar.setText("Redar Operation");
        btnRedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRedar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 185, 145, 44));

        display.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRotateActionPerformed

    private void btnShhotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShhotActionPerformed
        // TODO add your handling code here:
         if ((int) spiAmmo.getValue() != 0) {
            spiAmmo.setValue((int) spiAmmo.getValue() - 2);
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "⚠️ Out of Ammo! Refill required to continue combat operations\n                             Do You Want to Refill", "Warning", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                spiAmmo.setValue(200);
            }
        }
    }//GEN-LAST:event_btnShhotActionPerformed

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed
        // TODO add your handling code here:
        if ((int) spiSolder.getValue() != 0) {
            spiSolder.setValue((int) spiSolder.getValue() - 2);
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "⚠️ Out of Ammo! Refill required to continue combat operations\n                             Do You Want to Refill", "Warning", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                spiSolder.setValue(200);
            }
        }
    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
       mainController.setankMassage("Tank : "+txtMsg.getText()+"\n");

    }//GEN-LAST:event_btnSendActionPerformed

    private void chbPesitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPesitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPesitionActionPerformed

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgActionPerformed

    private void btnRedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRedarActionPerformed

    private void jSlider1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider1AncestorAdded
        // TODO add your handling code here:
        setSlider(jSlider1.getValue());
    }//GEN-LAST:event_jSlider1AncestorAdded
   
     public void setSlider(int value){
        display.setText(value+"");
    }
    @Override
    public void setAreaClear(boolean isClear){
         if(isClear==true){
           areaClearMsg.setText("Area is Clear");
       }else{
           areaClearMsg.setText("Area is Not Clear");
       }
    }
    @Override
    public void setBtnValue(int value){
        
        if(chbPesition.isSelected()){
            if(value>20){
                btnShhot.setEnabled(true);
                btnShhot.setBackground(Color.GREEN);
            }else{
                btnShhot.setEnabled(false);
                btnShhot.setBackground(new Color(102,102,255));
            }
            if(value>40){
                btnMissile.setEnabled(true);
                btnMissile.setBackground(Color.GREEN);
            }else{
                btnMissile.setEnabled(false);
                btnMissile.setBackground(new Color(102,102,255));
            }
            if(value>60){
                btnRedar.setEnabled(true);
                btnRedar.setBackground(Color.GREEN);
            }else{
                btnRedar.setEnabled(false);
                btnRedar.setBackground(new Color(102,102,255));
            }
            if(value>80){
                btnRotate.setEnabled(true);
                btnRotate.setBackground(Color.GREEN);
            }else{
                btnRotate.setEnabled(false);
                btnRotate.setBackground(new Color(102,102,255));
            }
        }else{
            btnShhot.setEnabled(false);
            btnRedar.setEnabled(false);
            btnRotate.setEnabled(false);
            btnMissile.setEnabled(false);
        }
    }
    @Override
    public void setMassageOtherBoxes(String massage){
        txtMassege.setText(massage);
    }
   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaClearMsg;
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotate;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShhot;
    private javax.swing.JCheckBox chbPesition;
    private javax.swing.JTextField display;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner spiAmmo;
    private javax.swing.JSpinner spiSolder;
    private javax.swing.JTextArea txtMassege;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
     @Override
    public void setprivateMassage(String massage) {
        txtMassege.setText(massage);
    }
}
